apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/fitsnips/argo-app-of-apps' 
    path: cert-manager
    targetRevision: HEAD
  destination:
    namespace: cert-manager
    name: in-cluster  
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
