apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/fitsnips/argo-app-of-apps' # Update to match your fork.
    path: guestbook
    targetRevision: HEAD
  destination:
    namespace: guestbook
    name: in-cluster # Update this value.
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
